note
	description: "[
		A wrapper class to generate 8-bit natural numbers.
		]"
	author: "Jimmy J. Johnson"

class
	JJ_NATURAL_8_RNG

inherit

	JJ_NATURAL_RNG [NATURAL_8]

create
	default_create,
	from_array

feature -- Access

	item: NATURAL_8
			-- The number generated by Current
		do
			Result := melg_item.as_natural_8
		end

end
